In [1]:
import pandas as pd
import numpy as np 
from keras.models import Sequential
from keras import layers, ops 
import keras
from keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
import tf2onnx
import os
import subprocess
import sys

In [2]:
X = np.load("../Data/Train_Data_V2/X_train_v2.npy")
Y = np.load("../Data/Y_train.npy")

print(X.shape)
print(Y.shape)

(15531, 14)
(20631,)

In [3]:
def AutoEncoder(X, input_dim, latent_dim, output_dim):
    model = Sequential([
        # Encoding phase
        keras.Input((input_dim, )),
        layers.Dense(16, name = 'Enc_layer1', kernel_initializer= 'he_normal', kernel_regularizer = keras.regularizers.l2(0.1)),
        layers.LeakyReLU(alpha = 0.01),
        layers.Dense(8, name = 'Enc_layer2', kernel_initializer= 'he_normal', kernel_regularizer = keras.regularizers.l2(0.1)),
        layers.LeakyReLU(alpha = 0.01),
        layers.Dense(latent_dim, name = 'Latent_Space', kernel_initializer= 'he_normal', kernel_regularizer = keras.regularizers.l2(0.1)), 
        layers.LeakyReLU(alpha = 0.01), 

        #Decoding phase
        layers.Dense(8, name = "dec_dense1", kernel_initializer= 'he_normal', kernel_regularizer = keras.regularizers.l2(0.1)),
        layers.LeakyReLU(alpha = 0.01),
        layers.Dense(16, name = "dec_dense2", kernel_initializer= 'he_normal', kernel_regularizer = keras.regularizers.l2(0.1)),
        layers.LeakyReLU(alpha = 0.01),
        layers.Dense(output_dim, name="output_layer", kernel_initializer= 'he_normal', kernel_regularizer = keras.regularizers.l2(0.1))
    ])
    # model.summary()
    return model

In [4]:
def train(X, epochs, batch_size): 
    input_dim = X.shape[1]
    latent_dim = 4
    output_dim = X.shape[1]
    model = AutoEncoder(X, input_dim, latent_dim, output_dim)

    model.compile(optimizer = keras.optimizers.Adam(learning_rate = 0.0005), loss = 'mse')

    early_stop = EarlyStopping(monitor='loss', patience=3, restore_best_weights=True)
    model.fit(X, 
              X,
              epochs = epochs,
              batch_size = batch_size,
              verbose = 1,
              shuffle = True,
              callbacks = [early_stop]
             )

    X_decoded = model.predict(X)

    return X_decoded, model

In [5]:
X_decoded, model = train(X, epochs=100, batch_size=256)

Epoch 1/100

/Users/shivaram/telemetry-anomaly-detector/.venv/lib/python3.11/site-packages/keras/src/layers/activations/leaky_relu.py:41: UserWarning: Argument `alpha` is deprecated. Use `negative_slope` instead.
  warnings.warn(

61/61 ━━━━━━━━━━━━━━━━━━━━ 1s 475us/step - loss: 12.8860
Epoch 2/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 403us/step - loss: 11.4105
Epoch 3/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 357us/step - loss: 10.1282
Epoch 4/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 353us/step - loss: 9.0021
Epoch 5/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - loss: 8.0063
Epoch 6/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - loss: 7.1222
Epoch 7/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - loss: 6.3357
Epoch 8/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - loss: 5.6350
Epoch 9/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 356us/step - loss: 5.0102
Epoch 10/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - loss: 4.4531
Epoch 11/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - loss: 3.9562
Epoch 12/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - loss: 3.5132
Epoch 13/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 352us/step - loss: 3.1185
Epoch 14/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - loss: 2.7668
Epoch 15/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 352us/step - loss: 2.4538
Epoch 16/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - loss: 2.1753
Epoch 17/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - loss: 1.9278
Epoch 18/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - loss: 1.7078
Epoch 19/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - loss: 1.5125
Epoch 20/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - loss: 1.3392
Epoch 21/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - loss: 1.1854
Epoch 22/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - loss: 1.0492
Epoch 23/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - loss: 0.9286
Epoch 24/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 360us/step - loss: 0.8218
Epoch 25/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - loss: 0.7273
Epoch 26/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 362us/step - loss: 0.6437
Epoch 27/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 364us/step - loss: 0.5698
Epoch 28/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - loss: 0.5046
Epoch 29/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - loss: 0.4470
Epoch 30/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - loss: 0.3961
Epoch 31/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 384us/step - loss: 0.3513
Epoch 32/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - loss: 0.3117
Epoch 33/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - loss: 0.2768
Epoch 34/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - loss: 0.2460
Epoch 35/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 364us/step - loss: 0.2188
Epoch 36/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - loss: 0.1949
Epoch 37/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - loss: 0.1738
Epoch 38/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 359us/step - loss: 0.1552
Epoch 39/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - loss: 0.1388
Epoch 40/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 360us/step - loss: 0.1243
Epoch 41/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 372us/step - loss: 0.1115
Epoch 42/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - loss: 0.1002
Epoch 43/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - loss: 0.0903
Epoch 44/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 368us/step - loss: 0.0815
Epoch 45/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - loss: 0.0738
Epoch 46/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - loss: 0.0670
Epoch 47/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 371us/step - loss: 0.0609
Epoch 48/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 376us/step - loss: 0.0556
Epoch 49/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - loss: 0.0509
Epoch 50/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - loss: 0.0468
Epoch 51/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - loss: 0.0432
Epoch 52/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - loss: 0.0400
Epoch 53/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 375us/step - loss: 0.0372
Epoch 54/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 367us/step - loss: 0.0347
Epoch 55/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - loss: 0.0326
Epoch 56/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - loss: 0.0307
Epoch 57/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - loss: 0.0290
Epoch 58/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 362us/step - loss: 0.0276
Epoch 59/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - loss: 0.0264
Epoch 60/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - loss: 0.0253
Epoch 61/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - loss: 0.0244
Epoch 62/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 359us/step - loss: 0.0236
Epoch 63/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 359us/step - loss: 0.0229
Epoch 64/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - loss: 0.0223
Epoch 65/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - loss: 0.0218
Epoch 66/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 356us/step - loss: 0.0214
Epoch 67/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 364us/step - loss: 0.0211
Epoch 68/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 362us/step - loss: 0.0208
Epoch 69/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 367us/step - loss: 0.0205
Epoch 70/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - loss: 0.0203
Epoch 71/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 360us/step - loss: 0.0201
Epoch 72/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 372us/step - loss: 0.0200
Epoch 73/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 357us/step - loss: 0.0199
Epoch 74/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - loss: 0.0198
Epoch 75/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - loss: 0.0197
Epoch 76/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 356us/step - loss: 0.0196
Epoch 77/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - loss: 0.0196
Epoch 78/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 360us/step - loss: 0.0196
Epoch 79/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 355us/step - loss: 0.0195
Epoch 80/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 364us/step - loss: 0.0195
Epoch 81/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - loss: 0.0195
Epoch 82/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - loss: 0.0195
Epoch 83/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 360us/step - loss: 0.0195
Epoch 84/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - loss: 0.0195
Epoch 85/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - loss: 0.0195
Epoch 86/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 357us/step - loss: 0.0194
Epoch 87/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 360us/step - loss: 0.0194
Epoch 88/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 355us/step - loss: 0.0194
Epoch 89/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - loss: 0.0194
Epoch 90/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - loss: 0.0194
Epoch 91/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 362us/step - loss: 0.0194
Epoch 92/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - loss: 0.0194
Epoch 93/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - loss: 0.0194
Epoch 94/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 359us/step - loss: 0.0194
Epoch 95/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - loss: 0.0194
Epoch 96/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - loss: 0.0194
Epoch 97/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - loss: 0.0194
Epoch 98/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - loss: 0.0194
Epoch 99/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 352us/step - loss: 0.0194
486/486 ━━━━━━━━━━━━━━━━━━━━ 0s 186us/step

In [7]:
X_pred = model.predict(X)
reconstruction_errors = np.mean(np.square(X - X_pred), axis=1)
reconstruction_errors

486/486 ━━━━━━━━━━━━━━━━━━━━ 0s 172us/step

array([0.01375769, 0.01076145, 0.01430544, ..., 0.03473158, 0.01816249,
       0.06215963], shape=(15531,))

In [8]:
model.save("../Model/AutoEncoder.keras")
print("Model saved sucessfully!")

Model saved sucessfully!

In [9]:
if not os.path.exists('../Model/model/tf_saved_model'):
    model.export('../Model/model/tf_saved_model')
    print("SavedModel artifact generated.")
else:
    print("Found existing SavedModel artifact from your last run. Perfect.")

# sys.executable forces the script to use the precise .venv Python 3.11 interpreter where tf2onnx lives
onnx_command = f"{sys.executable} -m tf2onnx.convert --saved-model ../Model/model/tf_saved_model --output ../Model/model/telemetry_autoencoder.onnx --opset 15"

# Run the terminal command safely
result = subprocess.run(onnx_command.split(), capture_output=True, text=True)

# 3. Verify the final result
if result.returncode == 0:
    print("\nSUCCESS! ")
else:
    print("\n Error ")
    print(result.stderr)

INFO:tensorflow:Assets written to: ../Model/model/tf_saved_model/assets

INFO:tensorflow:Assets written to: ../Model/model/tf_saved_model/assets

Saved artifact at '../Model/model/tf_saved_model'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 14), dtype=tf.float32, name='keras_tensor')
Output Type:
  TensorSpec(shape=(None, 14), dtype=tf.float32, name=None)
Captures:
  4846257552: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4846259280: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4846260432: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4846261008: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4846261392: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4846260816: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4846261968: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4846259664: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4846262736: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4846263312: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4846262352: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4846264272: TensorSpec(shape=(), dtype=tf.resource, name=None)
SavedModel artifact generated.

SUCCESS!

In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Enc_layer1 (Dense)              │ (None, 16)             │           240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ leaky_re_lu (LeakyReLU)         │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Enc_layer2 (Dense)              │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ leaky_re_lu_1 (LeakyReLU)       │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Latent_Space (Dense)            │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ leaky_re_lu_2 (LeakyReLU)       │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dec_dense1 (Dense)              │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ leaky_re_lu_3 (LeakyReLU)       │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dec_dense2 (Dense)              │ (None, 16)             │           144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ leaky_re_lu_4 (LeakyReLU)       │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_layer (Dense)            │ (None, 14)             │           238 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,504 (9.79 KB)

 Trainable params: 834 (3.26 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,670 (6.53 KB)

In [14]:
X_test = np.load("../Data/Test_Data/scaled_features.npy")
print(X_test)

[[0.54518074 0.31066057 0.26941255 ... 0.33333334 0.55813956 0.66183376]
 [0.15060242 0.3795509  0.222316   ... 0.41666666 0.68217057 0.6868268 ]
 [0.37650603 0.3466318  0.3222485  ... 0.41666666 0.72868216 0.7213477 ]
 ...
 [0.67168677 0.4820144  0.41475356 ... 0.5833333  0.37209302 0.4293013 ]
 [0.6174699  0.52212775 0.62643486 ... 0.5833333  0.4031008  0.51877934]
 [0.52409637 0.6666667  0.72147197 ... 0.6666667  0.43410853 0.40223694]]

In [50]:
X_test_pred = model.predict(X_test)
reconstruction = np.mean(np.square(X_test - X_test_pred), axis = 1)
mse = pd.DataFrame(reconstruction)
cids = np.load("../Data/Test_Data/identifiers.npy")
ids = pd.DataFrame(cids)
ids

410/410 ━━━━━━━━━━━━━━━━━━━━ 0s 177us/step

            0
0        1001
1        1002
2        1003
3        1004
4        1005
...       ...
13091  100194
13092  100195
13093  100196
13094  100197
13095  100198

[13096 rows x 1 columns]

In [54]:
data = pd.concat([ids, mse], axis=1) 
data.columns = ["composite_id", "mse"]

In [64]:
data["Unit_Number"] = data["composite_id"] // 1000
data["time_in_cycles"] = data["composite_id"] % 1000
col = ["composite_id"]
final_data = data.drop(columns = col)
final_data

            mse  Unit_Number  time_in_cycles
0      0.013007            1               1
1      0.024589            1               2
2      0.010541            1               3
3      0.013737            1               4
4      0.018620            1               5
...         ...          ...             ...
13091  0.031750          100             194
13092  0.028374          100             195
13093  0.029337          100             196
13094  0.030281          100             197
13095  0.043663          100             198

[13096 rows x 3 columns]

In [66]:
final_data[final_data['Unit_Number'] == 2]

         mse  Unit_Number  time_in_cycles
31  0.005991            2               1
32  0.003434            2               2
33  0.011168            2               3
34  0.009969            2               4
35  0.005795            2               5
36  0.008647            2               6
37  0.011309            2               7
38  0.007054            2               8
39  0.003195            2               9
40  0.003798            2              10
41  0.008482            2              11
42  0.007747            2              12
43  0.005480            2              13
44  0.007502            2              14
45  0.009567            2              15
46  0.007446            2              16
47  0.010658            2              17
48  0.005957            2              18
49  0.008803            2              19
50  0.003420            2              20
51  0.004467            2              21
52  0.006140            2              22
53  0.006244            2              23
54  0.005069            2              24
55  0.006349            2              25
56  0.007668            2              26
57  0.003812            2              27
58  0.004919            2              28
59  0.008250            2              29
60  0.004156            2              30
61  0.002830            2              31
62  0.005447            2              32
63  0.006288            2              33
64  0.007220            2              34
65  0.006372            2              35
66  0.004373            2              36
67  0.011780            2              37
68  0.003178            2              38
69  0.003628            2              39
70  0.004363            2              40
71  0.003704            2              41
72  0.005109            2              42
73  0.006097            2              43
74  0.003524            2              44
75  0.003528            2              45
76  0.004501            2              46
77  0.006932            2              47
78  0.005058            2              48
79  0.005252            2              49